package exceptionhandling;

public class Example2 {
public static void main(String[] args) {
	try{
		int arr[]= {1,3,4};
		System.out.println(arr[5]);
	}
	catch (ArrayIndexOutOfBoundsException e) {
		System.out.println(e.getMessage());
	}
	catch (ArithmeticException e) {
		System.out.println(e.getMessage());
	}
	
}
}
